apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-app1
    server: https://kubernetes.default.svc
  project: default
  source:
    - repoURL: 'git@github.com:VikasLall/argocdappofappskustomize.git'
      targetRevision: main
      path: apps-kustomization/app1
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
